/*
This file is part of Snappy Driver Installer.

Snappy Driver Installer is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Snappy Driver Installer is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Snappy Driver Installer.  If not, see <http://www.gnu.org/licenses/>.
*/

#include "main.h"

#define DEF_VAL(a) {TEXT(a),0,0},
#define DEF_STR(a) {TEXT(a),0,0},

entry_t language[STR_NM]=
{
    DEF_STR("STR_EMPTY")
    DEF_STR("STR_EMPTY_H")

// Lang info
    DEF_STR("STR_LANG_NAME")
    DEF_VAL("STR_LANG_CODE")

// Left panel
    DEF_STR("STR_SHOW_SYSINFO")
    DEF_STR("STR_SHOW_SYSINFO_H")

    DEF_STR("STR_INSTALL")
    DEF_STR("STR_INSTALL_H")
    DEF_STR("STR_SELECT_ALL")
    DEF_STR("STR_SELECT_ALL_H")
    DEF_STR("STR_SELECT_NONE")
    DEF_STR("STR_SELECT_NONE_H")

    DEF_STR("STR_LANG")
    DEF_STR("STR_LANG_H")
    DEF_STR("STR_THEME")
    DEF_STR("STR_THEME_H")
    DEF_STR("STR_EXPERT")
    DEF_STR("STR_EXPERT_H")

    DEF_STR("STR_OPENLOGS")
    DEF_STR("STR_OPENLOGS_H")
    DEF_STR("STR_SNAPSHOT")
    DEF_STR("STR_SNAPSHOT_H")
    DEF_STR("STR_EXTRACT")
    DEF_STR("STR_EXTRACT_H")
    DEF_STR("STR_DRVDIR")
    DEF_STR("STR_DRVDIR_H")

    DEF_STR("STR_SHOW_FOUND")
    DEF_STR("STR_SHOW_FOUND_H")
    DEF_STR("STR_SHOW_MISSING")
    DEF_STR("STR_SHOW_MISSING_H")
    DEF_STR("STR_SHOW_NEWER")
    DEF_STR("STR_SHOW_NEWER_H")
    DEF_STR("STR_SHOW_CURRENT")
    DEF_STR("STR_SHOW_CURRENT_H")
    DEF_STR("STR_SHOW_OLD")
    DEF_STR("STR_SHOW_OLD_H")
    DEF_STR("STR_SHOW_BETTER")
    DEF_STR("STR_SHOW_BETTER_H")
    DEF_STR("STR_SHOW_WORSE_RANK")
    DEF_STR("STR_SHOW_WORSE_RANK_H")

    DEF_STR("STR_SHOW_NOTFOUND")
    DEF_STR("STR_SHOW_NOTFOUND_H")
    DEF_STR("STR_SHOW_NF_MISSING")
    DEF_STR("STR_SHOW_NF_MISSING_H")
    DEF_STR("STR_SHOW_NF_UNKNOWN")
    DEF_STR("STR_SHOW_NF_UNKNOWN_H")
    DEF_STR("STR_SHOW_NF_STANDARD")
    DEF_STR("STR_SHOW_NF_STANDARD_H")

    DEF_STR("STR_SHOW_DISPLAY")
    DEF_STR("STR_SHOW_DISPLAY_H")
    DEF_STR("STR_SHOW_ONE")
    DEF_STR("STR_SHOW_ONE_H")
    DEF_STR("STR_SHOW_DUP")
    DEF_STR("STR_SHOW_DUP_H")
    DEF_STR("STR_SHOW_INVALID")
    DEF_STR("STR_SHOW_INVALID_H")

// Sysinfo
    DEF_STR("STR_SYSINF_WINDOWS")
    DEF_STR("STR_SYSINF_VERSION")
    DEF_STR("STR_SYSINF_PLATFORM")
    DEF_STR("STR_SYSINF_UPDATE")
    DEF_STR("STR_SYSINF_SERVICEPACK")
    DEF_STR("STR_SYSINF_SUITEMASK")
    DEF_STR("STR_SYSINF_PRODUCTTYPE")
    DEF_STR("STR_SYSINF_ENVIRONMENT")
    DEF_STR("STR_SYSINF_WINDIR")
    DEF_STR("STR_SYSINF_TEMP")
    DEF_STR("STR_SYSINF_MOTHERBOARD")
    DEF_STR("STR_SYSINF_PRODUCT")
    DEF_STR("STR_SYSINF_MODEL")
    DEF_STR("STR_SYSINF_MANUF")
    DEF_STR("STR_SYSINF_BATTERY")
    DEF_STR("STR_SYSINF_AC_STATUS")
    DEF_STR("STR_SYSINF_OFFLINE")
    DEF_STR("STR_SYSINF_ONLINE")
    DEF_STR("STR_SYSINF_UNKNOWN")
    DEF_STR("STR_SYSINF_FLAGS")
    DEF_STR("STR_SYSINF_HIGH")
    DEF_STR("STR_SYSINF_LOW")
    DEF_STR("STR_SYSINF_CRITICAL")
    DEF_STR("STR_SYSINF_CHARGING")
    DEF_STR("STR_SYSINF_NOBATTERY")
    DEF_STR("STR_SYSINF_CHARGED")
    DEF_STR("STR_SYSINF_LIFETIME")
    DEF_STR("STR_SYSINF_FULLLIFETIME")
    DEF_STR("STR_SYSINF_MINS")
    DEF_STR("STR_SYSINF_MONITORS")
    DEF_STR("STR_SYSINF_CM")
    DEF_STR("STR_SYSINF_INCH")
    DEF_STR("STR_SYSINF_WIDE")
    DEF_STR("STR_SYSINF_MISC")
    DEF_STR("STR_SYSINF_TYPE")
    DEF_STR("STR_SYSINF_LAPTOP")
    DEF_STR("STR_SYSINF_DESKTOP")
    DEF_STR("STR_SYSINF_LOCALE")
    DEF_STR("STR_SYSINF_CPU_ARCH")
    DEF_STR("STR_SYSINF_32BIT")
    DEF_STR("STR_SYSINF_64BIT")

// About
    DEF_STR("STR_ABOUT_VER")
    DEF_STR("STR_ABOUT_DEV_TITLE")
    DEF_STR("STR_ABOUT_DEV_LIST")
    DEF_STR("STR_ABOUT_TESTERS_TITLE")
    DEF_STR("STR_ABOUT_TESTERS_LIST")
    DEF_STR("STR_ABOUT_LICENSE")

// Driver popup windows
    DEF_STR("STR_HINT_UNKNOWN")
    DEF_STR("STR_HINT_ANALYSIS")
    DEF_STR("STR_HINT_DRP")
    DEF_STR("STR_HINT_DEVICE")
    DEF_STR("STR_HINT_HARDWAREID")
    DEF_STR("STR_HINT_COMPID")
    DEF_STR("STR_HINT_INSTDRV")
    DEF_STR("STR_HINT_AVAILDRV")
    DEF_STR("STR_HINT_AVAILDRVS")
    DEF_STR("STR_HINT_MANUF")
    DEF_STR("STR_HINT_PROVIDER")
    DEF_STR("STR_HINT_DATE")
    DEF_STR("STR_HINT_VERSION")
    DEF_STR("STR_HINT_ID")
    DEF_STR("STR_HINT_INF")
    DEF_STR("STR_HINT_SECTION")
    DEF_STR("STR_HINT_SCORE")
    DEF_STR("STR_HINT_SCROLL")

// Context menu
    DEF_STR("STR_CONT_INSTALL")
    DEF_STR("STR_CONT_SHOWALT")
    DEF_STR("STR_CONT_OPENINF")
    DEF_STR("STR_CONT_LOCATEINF")
    DEF_STR("STR_CONT_HWID_SEARCH")
    DEF_STR("STR_CONT_HWID_CLIP")

//
    DEF_STR("STR_RESTOREPOINT")
    DEF_STR("STR_OPENSNAPSHOT")
    DEF_STR("STR_EXTRACTFOLDER")

// Status
    DEF_STR("STR_STATUS_INVALID")
    DEF_STR("STR_STATUS_MISSING")
    DEF_STR("STR_STATUS_BETTER_NEW")
    DEF_STR("STR_STATUS_SAME_NEW")
    DEF_STR("STR_STATUS_WORSE_NEW")
    DEF_STR("STR_STATUS_BETTER_CUR")
    DEF_STR("STR_STATUS_SAME_CUR")
    DEF_STR("STR_STATUS_WORSE_CUR")
    DEF_STR("STR_STATUS_BETTER_OLD")
    DEF_STR("STR_STATUS_SAME_OLD")
    DEF_STR("STR_STATUS_WORSE_OLD")
    DEF_STR("STR_STATUS_DUP")
    DEF_STR("STR_STATUS_NF_MISSING")
    DEF_STR("STR_STATUS_NF_UNKNOWN")
    DEF_STR("STR_STATUS_NF_STANDARD")

// Virus
    DEF_STR("STR_VIRUS")
    DEF_STR("STR_VIRUS_AUTORUN")
    DEF_STR("STR_VIRUS_RECYCLER")
    DEF_STR("STR_VIRUS_HIDDEN")

// Status
    DEF_STR("STR_CLOSE_SNAPSHOT")
    DEF_STR("STR_EMPTYDRP")
    DEF_STR("STR_CLOSE_DRPEXT")

// Progress
    DEF_STR("STR_INST_EXTRACT")
    DEF_STR("STR_INST_INSTALL")
    DEF_STR("STR_INST_OK")
    DEF_STR("STR_INST_REBOOT")
    DEF_STR("STR_INST_FAILED")
    DEF_STR("STR_INST_EXTRACT_ALL")
    DEF_STR("STR_INST_INSTALL_ALL")
    DEF_STR("STR_INST_STOPPING")
    DEF_STR("STR_INDEXING")
    DEF_STR("STR_NEEDREBOOT")
    DEF_STR("STR_INST_COMPLITED")
    DEF_STR("STR_INST_COMPLITED_RB")
    DEF_STR("STR_INSR_CLOSE")
    DEF_STR("STR_OF")
    DEF_STR("STR_REST_CREATING")
    DEF_STR("STR_REST_CREATED")
    DEF_STR("STR_REST_FAILED")
};
