/*
This file is part of Snappy Driver Installer.

Snappy Driver Installer is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Snappy Driver Installer is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Snappy Driver Installer.  If not, see <http://www.gnu.org/licenses/>.
*/

enum
{
    STR_EMPTY=0,
    STR_EMPTY_H,

// Lang info
    STR_LANG_NAME,
    STR_LANG_CODE,

// Left panel
    STR_SHOW_SYSINFO,
    STR_SHOW_SYSINFO_H,

    STR_INSTALL,
    STR_INSTALL_H,
    STR_SELECT_ALL,
    STR_SELECT_ALL_H,
    STR_SELECT_NONE,
    STR_SELECT_NONE_H,

    STR_LANG,
    STR_LANG_H,
    STR_THEME,
    STR_THEME_H,
    STR_EXPERT,
    STR_EXPERT_H,

    STR_OPENLOGS,
    STR_OPENLOGS_H,
    STR_SNAPSHOT,
    STR_SNAPSHOT_H,
    STR_EXTRACT,
    STR_EXTRACT_H,
    STR_DRVDIR,
    STR_DRVDIR_H,

    STR_SHOW_FOUND,
    STR_SHOW_FOUND_H,
    STR_SHOW_MISSING,
    STR_SHOW_MISSING_H,
    STR_SHOW_NEWER,
    STR_SHOW_NEWER_H,
    STR_SHOW_CURRENT,
    STR_SHOW_CURRENT_H,
    STR_SHOW_OLD,
    STR_SHOW_OLD_H,
    STR_SHOW_BETTER,
    STR_SHOW_BETTER_H,
    STR_SHOW_WORSE_RANK,
    STR_SHOW_WORSE_RANK_H,

    STR_SHOW_NOTFOUND,
    STR_SHOW_NOTFOUND_H,
    STR_SHOW_NF_MISSING,
    STR_SHOW_NF_MISSING_H,
    STR_SHOW_NF_UNKNOWN,
    STR_SHOW_NF_UNKNOWN_H,
    STR_SHOW_NF_STANDARD,
    STR_SHOW_NF_STANDARD_H,

    STR_SHOW_DISPLAY,
    STR_SHOW_DISPLAY_H,
    STR_SHOW_ONE,
    STR_SHOW_ONE_H,
    STR_SHOW_DUP,
    STR_SHOW_DUP_H,
    STR_SHOW_INVALID,
    STR_SHOW_INVALID_H,

// Sysinfo
    STR_SYSINF_WINDOWS,
    STR_SYSINF_VERSION,
    STR_SYSINF_PLATFORM,
    STR_SYSINF_UPDATE,
    STR_SYSINF_SERVICEPACK,
    STR_SYSINF_SUITEMASK,
    STR_SYSINF_PRODUCTTYPE,
    STR_SYSINF_ENVIRONMENT,
    STR_SYSINF_WINDIR,
    STR_SYSINF_TEMP,
    STR_SYSINF_MOTHERBOARD,
    STR_SYSINF_PRODUCT,
    STR_SYSINF_MODEL,
    STR_SYSINF_MANUF,
    STR_SYSINF_BATTERY,
    STR_SYSINF_AC_STATUS,
    STR_SYSINF_OFFLINE,
    STR_SYSINF_ONLINE,
    STR_SYSINF_UNKNOWN,
    STR_SYSINF_FLAGS,
    STR_SYSINF_HIGH,
    STR_SYSINF_LOW,
    STR_SYSINF_CRITICAL,
    STR_SYSINF_CHARGING,
    STR_SYSINF_NOBATTERY,
    STR_SYSINF_CHARGED,
    STR_SYSINF_LIFETIME,
    STR_SYSINF_FULLLIFETIME,
    STR_SYSINF_MINS,
    STR_SYSINF_MONITORS,
    STR_SYSINF_CM,
    STR_SYSINF_INCH,
    STR_SYSINF_WIDE,
    STR_SYSINF_MISC,
    STR_SYSINF_TYPE,
    STR_SYSINF_LAPTOP,
    STR_SYSINF_DESKTOP,
    STR_SYSINF_LOCALE,
    STR_SYSINF_CPU_ARCH,
    STR_SYSINF_32BIT,
    STR_SYSINF_64BIT,

// About
    STR_ABOUT_VER,
    STR_ABOUT_DEV_TITLE,
    STR_ABOUT_DEV_LIST,
    STR_ABOUT_TESTERS_TITLE,
    STR_ABOUT_TESTERS_LIST,
    STR_ABOUT_LICENSE,

// Driver popup windows
    STR_HINT_UNKNOWN,
    STR_HINT_ANALYSIS,
    STR_HINT_DRP,
    STR_HINT_DEVICE,
    STR_HINT_HARDWAREID,
    STR_HINT_COMPID,
    STR_HINT_INSTDRV,
    STR_HINT_AVAILDRV,
    STR_HINT_AVAILDRVS,
    STR_HINT_MANUF,
    STR_HINT_PROVIDER,
    STR_HINT_DATE,
    STR_HINT_VERSION,
    STR_HINT_ID,
    STR_HINT_INF,
    STR_HINT_SECTION,
    STR_HINT_SCORE,
    STR_HINT_SCROLL,

// Context menu
    STR_CONT_INSTALL,
    STR_CONT_SHOWALT,
    STR_CONT_OPENINF,
    STR_CONT_LOCATEINF,
    STR_CONT_HWID_SEARCH,
    STR_CONT_HWID_CLIP,

// Misc
    STR_OPENSNAPSHOT,
    STR_EXTRACTFOLDER,

// Device status
    STR_STATUS_NOTPRESENT,
    STR_STATUS_DISABLED,
    STR_STATUS_DEVPROBLEM,
    STR_STATUS_DRVPROBLEM,
    STR_STATUS_RUNNING,
    STR_STATUS_STOPPED,

// Driver status
    STR_STATUS_INVALID,
    STR_STATUS_MISSING,
    STR_STATUS_NOTSIGNED,
    STR_STATUS_BETTER_NEW,
    STR_STATUS_SAME_NEW,
    STR_STATUS_WORSE_NEW,
    STR_STATUS_BETTER_CUR,
    STR_STATUS_SAME_CUR,
    STR_STATUS_WORSE_CUR,
    STR_STATUS_BETTER_OLD,
    STR_STATUS_SAME_OLD,
    STR_STATUS_WORSE_OLD,
    STR_STATUS_DUP,
    STR_STATUS_NF_MISSING,
    STR_STATUS_NF_UNKNOWN,
    STR_STATUS_NF_STANDARD,

// Virus
    STR_VIRUS,
    STR_VIRUS_AUTORUN,
    STR_VIRUS_RECYCLER,
    STR_VIRUS_HIDDEN,

// Status
    STR_CLOSE_SNAPSHOT,
    STR_EMPTYDRP,
    STR_CLOSE_DRPEXT,
    STR_NOUPDATES,
    STR_INITIALIZING,

// Progress
    STR_INST_EXTRACT,
    STR_INST_INSTALL,
    STR_INST_OK,
    STR_INST_REBOOT,
    STR_INST_FAILED,

    STR_INST_INSTALLING,
    STR_INST_COMPLITED,
    STR_INST_COMPLITED_RB,
    STR_INST_CLOSE,

    STR_EXTR_EXTRACTING,
    STR_EXTR_OK,
    STR_EXTR_FAILED,

    STR_INST_STOPPING,
    STR_INDEXING,
    STR_OF,

    STR_RESTOREPOINT,
    STR_REST_CREATING,
    STR_REST_CREATED,
    STR_REST_FAILED,

    STR_NM
};
